---
- hosts: pies
  remote_user: pi
  sudo: yes
  tasks:
    # install python3, pip3, pymodbus3 
    #- name: pip
      #command: pip install pymodbus

    #- name: stuff
      #command: wget http://10.160.80.4:8000/alarm.py

    - name: let there be light
      command: python /home/pi/led.py
    
    #- name: run modbus
     #   command: python /home/pi/alarm.py
